# Project information
site_name: Trio documentation

site_description: Documentation of Trio, an Automated Insulin Delivery system for iOS.
site_url: https://docs.diy-trio.org
site_author: Trio Community

# Repository
repo_name: nightscout/trio-docs
repo_url: https://github.com/nightscout/trio-docs
edit_uri: edit/dev/docs/

# Copyright
copyright: Trio Community

extra_css:
  - assets/stylesheets/primary_color.css
  - assets/stylesheets/extra.css

extra_javascript:
  - assets/javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

# Configuration
theme:
  name: material
  language: en
  logo: assets/images/trio-logo.png
  favicon: assets/images/favicon.ico
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-auto
        name: Switch to auto (use System Preferences)

  features:
    - announce.dismiss
    - content.action.edit
    - content.code.copy
    - content.tabs.link
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - toc.follow
    - toc.integrate

# Plugins - install using: pip3 install -r requirements.txt
plugins:
  - exclude:
      glob:
        - "**/download/download.txt"
  - include-markdown:
      preserve_includer_indent: true
      dedent: true
      comments: false
  - macros:
      render_by_default: false
      on_error_fail: true
      on_undefined: strict
      j2_block_start_string: "[[%"
      j2_block_end_string: "%]]"
  - search

# Customizations
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nightscout/trio-docs
      name: Trio on GitHub
    - icon: fontawesome/brands/discord
      link: https://discord.gg/FnwFEFUwXE
      name: Trio on Discord
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/groups/diytrio
      name: Trio on Facebook
  version: "0.9"
  release: "0.9.5"

# Extensions
# - These are carefully chosen to work with pandoc markdown support for whole document translation
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true
      toc_depth: 3

# Validation
validation:
  nav:
    omitted_files: info
    not_found: warn
    absolute_links: info
  links:
    not_found: warn
    absolute_links: info
    unrecognized_links: info

not_in_nav: |
  **/download/*.md

# Page tree
nav:
  - Home: ./EN/index.md
  - Overview:
      - Introduction: ./EN/Getting-Started/Overview.md
      - App Overview: ./EN/operate/interface.md
      - New User Guide: ./EN/Setup/New-User-Setup.md
      - Coming from Other AID Systems: ./EN/Configuration/transition-qa.md
      - Common Issues: ./EN/operate/troubleshoot.md
  - Device Compatibility:
      - iPhones & Watches: ./EN/Getting-Started/iphone.md
      - Pumps: ./EN/Getting-Started/pump.md
      - CGMs: ./EN/settings/devices/cgm.md
  - Build/Update Trio:
      - Build Instructions: ./EN/operate/build.md
      - Customizations: ./EN/operate/customize.md
  - User Settings (all users):
      - Trio Main Preferences: ./EN/settings/configuration/preferences/trio.md
      - Pump, CGM, Watch: ./EN/Configuration/Devices.md
      - Additional Pump Settings: ./EN/settings/configuration/pumpsettings.md
      - Basal: ./EN/settings/configuration/basalprofile.md
      - ISF: ./EN/settings/configuration/insulinsensitivities.md
      - CR: ./EN/settings/configuration/carbratios.md
      - Target Glucose: ./EN/settings/configuration/targetglucose.md
      - Main Settings: ./EN/settings/configuration/preferences/mainsettings.md
      - SMB & UAM: ./EN/settings/configuration/concepts/smb-uam.md
      - Close the Loop: ./EN/Configuration/Configure.md
  - Optional Settings (all users):
      - Apple Health: ./EN/settings/services/applehealth.md
      - FPU: ./EN/settings/services/fatprotein.md
      - Nightscout: ./EN/settings/services/nightscout.md
      - Notifications: ./EN/settings/services/notifications.md
      - SMB Settings: ./EN/settings/configuration/preferences/smbsettings.md
      - Temp Targets: ./EN/operate/temptarget.md
  - Advanced Settings (advanced users):
      - Autotune: ./EN/settings/configuration/autotune.md
      - Dynamic Settings: ./EN/settings/configuration/concepts/autosens-dynamic.md
      - Sigmoid: ./EN/settings/configuration/concepts/sigmoid.md
      - Dynamic Settings Explained: ./EN/settings/configuration/preferences/dynamicsettings.md
      - Other Settings: ./EN/settings/configuration/preferences/othersettings.md
      - Sensitivity Settings: ./EN/settings/configuration/preferences/targetsettings.md
  - Resources:
      - Citations: ./EN/resources/citations.md
